// bitmap file 
// (c) Technion IIT, Department of Electrical Engineering 2021 
// generated bythe automatic Python tool 
 
 
 module slowBitMap (

					input	logic	clk, 
					input	logic	resetN, 
					input logic	[10:0] offsetX,// offset from top left  position 
					input logic	[10:0] offsetY, 
					input	logic	InsideRectangle, //input that the pixel is within a bracket 
					input logic draw,
					input logic collision_any_ball_any_gift,
					input logic can_cont,
 
					output	logic	drawingRequest, //output that the pixel should be dispalyed 
					output	logic	[7:0] RGBout,  //rgb value from the bitmap 
					output	logic	[3:0] HitEdgeCode //one bit per edge 
 ) ; 
 
 
// generating the bitmap 
 

localparam logic [7:0] TRANSPARENT_ENCODING = 8'h11 ;// RGB value in the bitmap representing a transparent pixel  
logic[0:31][0:31][7:0] object_colors = {
	{8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'hd8,8'hd8,8'h90,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11},
	{8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'hd8,8'h11,8'h11,8'h11,8'h90,8'hd9,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11},
	{8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'hd8,8'h11,8'hd8,8'hd8,8'hd8,8'h11,8'hd9,8'hd9,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11},
	{8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'hd8,8'h11,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'h11,8'h88,8'hd9,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11},
	{8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'hd8,8'h11,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'h11,8'hd8,8'hda,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11},
	{8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'hd8,8'h11,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'h11,8'hd8,8'hd9,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11},
	{8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'hd8,8'h11,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'h11,8'h90,8'hd9,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11},
	{8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'hd8,8'h11,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'h11,8'hd8,8'hd9,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11},
	{8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'hd8,8'h11,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'h11,8'h88,8'hd9,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11},
	{8'h11,8'h11,8'h11,8'h11,8'h11,8'hd8,8'h11,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'h11,8'hd8,8'hda,8'h11,8'h11,8'h11,8'h11,8'h11},
	{8'h11,8'h11,8'h11,8'h11,8'hd8,8'h11,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'h11,8'hd8,8'hd9,8'h11,8'h11,8'h11,8'h11},
	{8'h11,8'h11,8'h11,8'hd8,8'h11,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'h11,8'hd9,8'hd9,8'h11,8'h11,8'h11},
	{8'h11,8'h11,8'hd8,8'h11,8'hd8,8'hd8,8'hd8,8'h00,8'h00,8'hd8,8'hd8,8'h00,8'hd8,8'hd8,8'hd8,8'hd8,8'h00,8'h00,8'h00,8'hd8,8'h00,8'hd8,8'hd8,8'hd8,8'h00,8'hd8,8'hd8,8'h11,8'hd8,8'hd9,8'h11,8'h11},
	{8'h11,8'hd8,8'h11,8'hd9,8'hd8,8'hd8,8'h00,8'hd8,8'hd8,8'h00,8'hd8,8'h00,8'hd8,8'hd8,8'hd8,8'hd8,8'h00,8'hd8,8'h00,8'hd8,8'h00,8'hd8,8'h48,8'hd8,8'h00,8'hd8,8'hd8,8'hd8,8'h11,8'hd8,8'hda,8'h11},
	{8'hd9,8'h11,8'hd8,8'hd8,8'hd8,8'hd8,8'h00,8'hd8,8'hd8,8'hd8,8'hd8,8'h00,8'hd8,8'hd8,8'hd8,8'h00,8'hd8,8'hd8,8'hd0,8'h00,8'h00,8'hd8,8'h00,8'hd8,8'h00,8'hd8,8'hd8,8'hd8,8'hd8,8'h11,8'hd8,8'hda},
	{8'hd8,8'h11,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'h00,8'h00,8'hd8,8'hd8,8'h00,8'hd8,8'hd8,8'hd8,8'h00,8'hd8,8'hd8,8'hd8,8'h00,8'h00,8'hd8,8'h00,8'hd8,8'h00,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'h11,8'hd8},
	{8'hd8,8'h11,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'h00,8'h00,8'hd8,8'h00,8'hd8,8'hd8,8'hd8,8'h00,8'hd8,8'hd8,8'hd8,8'h00,8'h00,8'h00,8'h00,8'hd8,8'h00,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'h11,8'hd8},
	{8'hda,8'h11,8'hd9,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'h00,8'hd8,8'h00,8'hd8,8'hd8,8'hd8,8'h00,8'hd8,8'hd8,8'h88,8'h00,8'h00,8'h00,8'h00,8'h00,8'h00,8'hd8,8'hd8,8'hd8,8'hd8,8'h11,8'hd8,8'h11},
	{8'h11,8'hd8,8'h11,8'h88,8'hd8,8'hd8,8'h00,8'hd8,8'hd8,8'h00,8'hd8,8'h00,8'hd8,8'hd8,8'hd8,8'hd8,8'h00,8'hd8,8'h00,8'hd8,8'h00,8'h00,8'h00,8'h00,8'h00,8'hd8,8'hd8,8'hd8,8'h11,8'hd8,8'hd2,8'h11},
	{8'h11,8'h11,8'hd8,8'h11,8'hd8,8'hd8,8'hd8,8'h00,8'h00,8'hd8,8'hd8,8'h00,8'h00,8'h00,8'h00,8'hd8,8'h00,8'h00,8'h00,8'hd8,8'hd8,8'hd9,8'h90,8'hd8,8'hd8,8'hd8,8'hd8,8'h11,8'hd8,8'h11,8'h11,8'h11},
	{8'h11,8'h11,8'h11,8'hd8,8'h11,8'hd9,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'h11,8'hd8,8'h11,8'h11,8'h11,8'h11},
	{8'h11,8'h11,8'h11,8'h11,8'hd8,8'h11,8'h48,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'h11,8'hd8,8'hda,8'h11,8'h11,8'h11,8'h11},
	{8'h11,8'h11,8'h11,8'h11,8'h11,8'hd8,8'h11,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'h11,8'hd8,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11},
	{8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'hd8,8'h11,8'h48,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'h11,8'hd8,8'hd2,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11},
	{8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'hd8,8'h11,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'h11,8'hd8,8'hda,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11},
	{8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'hd8,8'h11,8'hd9,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'h11,8'hd8,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11},
	{8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'hd8,8'h11,8'hd9,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'h11,8'hd8,8'hd1,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11},
	{8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'hd8,8'h11,8'hd9,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'h11,8'hd8,8'hda,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11},
	{8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'hd8,8'h11,8'hd8,8'hd8,8'hd8,8'hd8,8'hd8,8'h11,8'hd9,8'hd1,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11},
	{8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'hd8,8'h11,8'hd8,8'hd8,8'hd8,8'h11,8'hd0,8'hd1,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11},
	{8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'hd8,8'h11,8'h11,8'h11,8'hd9,8'hd9,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11},
	{8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'hd8,8'hd8,8'hd8,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11,8'h11}};

 
 
//////////--------------------------------------------------------------------------------------------------------------= 
//hit bit map has one bit per edge:  hit_colors[3:0] =   {Left, Top, Right, Bottom}	 
//there is one bit per edge, in the corner two bits are set  
 logic [0:3] [0:3] [3:0] hit_colors = 
		   {16'hC446,     
			16'h8C62,    
			16'h8932, 
			16'h9113}; 
 // pipeline (ff) to get the pixel color from the array 	 
//////////--------------------------------------------------------------------------------------------------------------= 
logic kill_gift = 0;
always_ff@(posedge clk or negedge resetN) 
begin 
	if(!resetN) begin 
		RGBout <=	8'h00; 
		HitEdgeCode <= 4'h0; 
		kill_gift <= 0;
	end 
	else begin 
		RGBout <= TRANSPARENT_ENCODING ; // default  
		HitEdgeCode <= 4'h0; 
 
		if (InsideRectangle == 1'b1 ) 
		begin // inside an external bracket  
			HitEdgeCode <= hit_colors[offsetY >> 3][offsetX >> 3 ]; // get hitting edge from the colors table
			RGBout <= object_colors[offsetY][offsetX]; 
		end  	 
		if(draw == 1 && collision_any_ball_any_gift) begin
			kill_gift <= 1;
		end
		else if(can_cont) begin
			kill_gift <= 0;
		end
	end 
end 
 
//////////--------------------------------------------------------------------------------------------------------------= 
// decide if to draw the pixel or not 
assign drawingRequest = (RGBout != TRANSPARENT_ENCODING && draw && !kill_gift) ? 1'b1 : 1'b0 ; // get optional transparent command from the bitmpap   
 
endmodule 
